feat: add esbuild
njfamirm/12fy pull request #14
Opened 2023-08-19 10:35 UTC by njfamirm

2023-08-19 16:48 UTC, AliMD commented on config/esbuild.js
> +    entryPoints: [`site/_js/main.ts`],
مگه قرار نیست از ورودی بگیره؟
پس این نباید کار کنه!

2023-08-19 16:48 UTC, AliMD commented on config/esbuild.js
> +    entryPoints: [`site/_js/main.ts`],
مثل CSS مگه نباید نوشته بشه؟!
من نمیدونم روش درستش چیه
یک مدل که کار کنه با مثلا استفاده بده ببینم چی میشه

2023-08-19 16:50 UTC, AliMD requested changes
مثل CSS مگه نباید نوشته بشه؟!
من نمیدونم روش درستش چیه و دقیقا میخوایم چیکار کنیم
از طرفی کد‌‌های فعلی رو هم میخوایم import و threeshake کنیم
یک مدل که کار کنه با مثلا استفاده بده ببینم چی میشه

2023-08-19 16:50 UTC, AliMD commented
اولیت این خیلی پایینه

2023-08-19 16:50 UTC, njfamirm commented on config/esbuild.js
> +    entryPoints: [`site/_js/main.ts`],
فیلتر نیست
کلا بیلد جدا شده و فایل خروجی میده

2023-08-20 12:01 UTC, AliMD approved these changes

2023-08-20 12:07 UTC, merged